### ISSUE TITLE
Version requirement of `Text` package

### ISSUE THREAD

**Issue by neocxi** [selectel/bson-haskell#11]
Thanks for making the awesome bson package. I’m wondering if you can modify the dependency of bson to allow for more recent versions of `text` packages? I’m using persistent-mongoDB that ultimately depends on bson, but since bson requires an old version of text there will be conflict if `text` package’s more recent version is required elsewhere in the build.

Currently I’m removing this constraint manually when i install bson to work around it and it doesn’t seem to break it with 1.*’s text. Hope you can consider updating it.

**Comment by superbobry** [comment]
Fixed by @TomMD in 056d17274641e809b0cb9028eb2cc49935be90f4.
