### ISSUE TITLE
Lower version bound on binary

### ISSUE THREAD

**Issue by davidsd** [selectel/bson-haskell#8]
It looks like Data.Bson requires the lookAhead function in Data.Binary.Get.  This was added in version 0.7.0.  Adding a lower bound

binary >= 0.7

to bson.cabal should avoid some compilation errors.

**Comment by gregwebs** [comment]
Can we fix this? I can make the changes if you give me access.

**Comment by knsd** [comment]
Already on hackage, sorry for delay.
